# This is a template/reference for the Homebrew formula that gets automatically
# generated and pushed to https://github.com/conallob/homebrew-tap
#
# DO NOT manually edit this file - it's just for reference.
# The actual formula is automatically generated by .github/workflows/release.yml

class OmnifocusScripts < Formula
  desc "Automation scripts for OmniFocus task management"
  homepage "https://github.com/conallob/omnifocus-scripts"
  url "https://github.com/conallob/omnifocus-scripts/archive/vVERSION.tar.gz"
  sha256 "SHA256_HASH_HERE"
  version "VERSION"
  license "MIT"

  depends_on :macos

  def install
    # Install all scripts to share directory
    share.install Dir["*"]

    # Create symlink for easy access
    (prefix/"omnifocus-scripts").install_symlink share
  end

  def caveats
    <<~EOS
      OmniFocus scripts have been installed to:
        #{opt_share}

      Available scripts:
        • Slack Integration: #{opt_share}/slack-integration/
        • Reschedule Overdue: #{opt_share}/reschedule-overdue/

      For detailed usage instructions, see:
        #{opt_share}/README.md
    EOS
  end

  test do
    assert_predicate share/"README.md", :exist?
    assert_predicate share/"slack-integration", :exist?
    assert_predicate share/"reschedule-overdue", :exist?
  end
end
